//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindShadow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Father_Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Sex { get; set; }
        public string Religion { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string Address { get; set; }
        public string Last_qualifying_exam { get; set; }
        public string Board_name { get; set; }
        public Nullable<int> Passing_year { get; set; }
        public Nullable<int> Marks_obtain { get; set; }
        public string Marks_upload { get; set; }
        public byte[] Marks_upload1 { get; set; }
        public Nullable<int> C_10th_passing_year { get; set; }
        public Nullable<int> C_10th_marks_obtain { get; set; }
        public string C_10th_marksheet_upload { get; set; }
        public byte[] C_10th_marksheet_upload1 { get; set; }
        public Nullable<int> C_12th_passing_year { get; set; }
        public Nullable<int> C_12th_marks_obtain { get; set; }
        public string C_12th_marksheet_upload { get; set; }
        public byte[] C_12th_matksheet_upload1 { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Doctor_id { get; set; }
        public string Password { get; set; }
    }
}
