//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindShadow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gardian
    {
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Phone_No { get; set; }
        public string Email { get; set; }
        public string Relation { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string Patient_Name { get; set; }
        public Nullable<System.DateTime> Patient_DOB { get; set; }
        public Nullable<int> Patient_Age { get; set; }
        public string Patient_Gender { get; set; }
        public string Patient_Address { get; set; }
        public string Patient_Phone_No { get; set; }
        public string Gardian_Id { get; set; }
        public string Password { get; set; }
    }
}
